#!/bin/bash

[ -d .setup/keys ] || mkdir -p .setup/keys


echo "### Generate keys for https encryption"
openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout .setup/keys/mykey.key \
    -out .setup/keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F" && \
    chmod a+r .setup/keys/mykey.key

echo "### Download password generating utility"
curl -fSL https://github.com/dddlab/jupyter-passwd/releases/download/v0.1.1/hash-password \
    -o .setup/hash-password && \
    chmod u+x .setup/hash-password

cat <<EOF > .env
## generated by setup.sh
## variables for docker-compose
HOST_DIR=${PWD}
CERT_DIR=${PWD}/.setup/keys
PASSWD=$(.setup/hash-password | tail -n1)
EOF